name: geog0111
channels: 
    - conda-forge
dependencies:
    - numpy
    - beautifulsoup4
    - lxml
    - cryptography
    - python>=3.6
    - numpy 
    - scipy
    - matplotlib 
    - gdal>2.2
    - pandas  
    - requests
    - earthengine-api
    - ipython
    - jupyter
    - matplotlib
    - ipywidgets
    - jupyter_contrib_nbextensions
    - xeus=0.23.14 
    - xeus-python=0.7.1 
    - notebook=6 
    - jupyterlab=2 
    - ptvsd 
    - nodejs
    - ipympl
    - ipywidgets

